04_Rails_Blogger/Blogger/config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'
  resources :articles do
	resources :comments
  end
  resources :tags
  resources :authors
  
  resources :author_sessions, only: [ :new, :create, :destroy ]
  get 'login' => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'
  
end

04_Rails_Blogger/Blogger/app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments
	has_many :taggings
	has_many :tags, through: :taggings
	
	has_attached_file :image
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
	
	def tag_list
		self.tags.collect do |tag|
			tag.name
		end.join(", ")
	end
	
	def tag_list=(tags_string)
		tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
		new_or_found_tags = tag_names.collect {|name| Tag.find_or_create_by(name: name) }
		self.tags = new_or_found_tags
	end
end

04_Rails_Blogger/Blogger/app/models/author.rb
class Author < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "Should match confirmation", if: :password
end

04_Rails_Blogger/Blogger/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :article
end

04_Rails_Blogger/Blogger/app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :articles, through: :taggings
end

04_Rails_Blogger/Blogger/app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

04_Rails_Blogger/Blogger/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	include ArticlesHelper
	before_filter :require_login, except: [:index, :show]
	
	def index
		@articles = Article.all
	end
	
	def new
		@article = Article.new
	end
	
	def show
		@article = Article.find(params[:id])

	    @comment = Comment.new
	    @comment.article_id = @article.id		
	end
	
	
    def edit
        @article = Article.find(params[:id])
    end
	
	def create
		@article = Article.new(article_params)
		@article.save
		
		flash.notice = "Article '#{@article.title}' Created!"
		
		redirect_to article_path(@article)
	end
	
	def update
		@article = Article.find(params[:id])	
		@article.update(article_params)
		
		flash.notice = "Article '#{@article.title}' updated!"
		
		redirect_to article_path(@article)
	end
	
	def destroy
		@article = Article.find(params[:id])
		@article.destroy!
		
		flash.notice = "Article '#{@article.title}' Deleted!"
		
		redirect_to articles_path
	end
	
end

04_Rails_Blogger/Blogger/app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
  def new
  end

  def create
    if login(params[:email], params[:password])
      redirect_back_or_to(articles_path, notice: 'Logged in successfully.')
    else
      flash.now.alert = "Login failed."
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(:authors, notice: 'Logged out!')
  end
end

04_Rails_Blogger/Blogger/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_filter :zero_authors_or_authenticated, only: [:new, :create]
  before_filter :require_login, except: [new, :create]

  def zero_authors_or_authenticated
    unless Author.count == 0 || current_user
      redirect_to root_path
      return false
    end
  end
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

04_Rails_Blogger/Blogger/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :require_login, except: [:create]
	
	def create
		@comment = Comment.new(comment_params)
		@comment.article_id = params[:article_id]
		
		@comment.save
		
		redirect_to article_path(@comment.article)
	end
	
	def comment_params
		params.require(:comment).permit(:author_name, :body)
	end
end

04_Rails_Blogger/Blogger/app/controllers/tags_controller.rb
class TagsController < ApplicationController
	before_filter :require_login, only: [:destroy]
	
	def index
		@tags = Tag.all
	end
	
	def show
		@tag = Tag.find(params[:id])
	end
	
	def destroy
		@tag = Tag.find(params[:id])
		@tag.destroy!
		
		flash.notice = "Tag '#{@tag.name}' Deleted!"
		
		redirect_to tags_path
	end
end

04_Rails_Blogger/Blogger/app/helpers/articles_helper.rb
module ArticlesHelper
	def article_params
		params.require(:article).permit(:title, :body, :tag_list, :image)
	end
end

04_Rails_Blogger/Blogger/app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

04_Rails_Blogger/Blogger/app/helpers/authors_helper.rb
module AuthorsHelper
end

04_Rails_Blogger/Blogger/app/helpers/tags_helper.rb
module TagsHelper
end

04_Rails_Blogger/Blogger/app/views/articles/_comment.html.erb
<div>
	<h4>Comment by: <%= comment.author_name %></h4>
	<p class="comment"><%= comment.body %></p>
	<p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> ago </p>
</div>

04_Rails_Blogger/Blogger/app/views/articles/_form.html.erb
<%= form_for(@article, html:{multipart: true}) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
	<%= f.label :tag_list %><br />
	<%= f.text_field :tag_list %>
  </p>
  <p>
	  <% if @article.image.exists? %>
		<%= image_tag @article.image.url %><br />
	  <% end %>
	  <%= f.label :image, "Attach an Image" %><br />
	  <%= f.file_field :image %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

04_Rails_Blogger/Blogger/app/views/articles/edit.html.erb
<h1>Edit an Article</h1>

<%= render partial: "form" %>

04_Rails_Blogger/Blogger/app/views/articles/index.html.erb
<h1> All Articles </h1>

<ul id="articles">
	<% @articles.each do |article| %>
		<li>
			<%= link_to article.title, article_path(article) %>
		</li>
	<% end %>

</ul>
<% if logged_in? %>
<%= link_to "Create New Article", new_article_path, class: "new_article" %>
<% end %>

04_Rails_Blogger/Blogger/app/views/articles/new.html.erb
<h1> Create A New Article </h1>

<%= render partial: 'form' %>

04_Rails_Blogger/Blogger/app/views/articles/show.html.erb
<h1> <%= @article.title %></h1>
<br />
<p>
	Tags:
	<% @article.tags.each do |tag| %>
		<%= link_to tag.name, tag_path(tag) %>
	<% end %>
</p>
<hr />
<br />

<% if @article.image.exists? %>
	<p>
	<%= image_tag @article.image.url %>
	</p>
<% end %>

<br />
<p> <%= @article.body %> </p>
<% if logged_in? %>
<br />
<ul class='btn-nav'>
	<li> <%= link_to "Edit", edit_article_path , class: "btn-new fancy-button-reset-base-class"%> </li>
	<li><%= button_to "Delete", article_path(@article),
				  method: :delete,
				  data: { confirm: "Are you sure?" } %></li>
</ul>
<% end %>
<br />

<h3> Comments (<%= @article.comments.size %>)</h3>
<%= render partial: "articles/comment", collection: @article.comments %>
<br />
<%= render partial: "comments/form" %>
<br />
<%= link_to "<< Back To Articles List", articles_path %>